#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using TestMVC;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Test/Test.cshtml")]
    public partial class _Views_Test_Test_cshtml : System.Web.Mvc.WebViewPage<TestMVC.Models.TestModel>
    {
        public _Views_Test_Test_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" src=\"/Scripts/Test.js\"");

WriteLiteral("></script>\r\n<br />\r\n<br />\r\n");

            
            #line 9 "..\..\Views\Test\Test.cshtml"
Write(Html.HiddenFor(p => p.ClickCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Click Me\"");

WriteLiteral(" name=\"btnClickTest\"");

WriteLiteral(" onclick=\"ClickCounter()\"");

WriteLiteral(" style=\"width:150px;height:30px;\"");

WriteLiteral("/>\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCounter\"");

WriteLiteral("  style=\"width:150px;height:30px;\"");

WriteLiteral(" />\r\n");

        }
    }
}
#pragma warning restore 1591
